In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
#import data
data = pd.read_csv("../data/ModelData_2.csv")
data.head()

,Servings/s,Calories/s,Fat/s,Sat_Fat/s,Trans_Fat/s,Mono_Fat/s,Poly_Fat/s,Carbs/s,Fiber/s,Sugars/s,...,Vit_D/s,Vit_E/s,Vit_K/s,Water/s,CarbScore,CholoScore,TotalFatScore,SugarScore,HealthyGradScore,HealthyScore
0,1,100.783428,3.706567,0.478814,0.001744,1.190110,1.662028,12.935162,2.351610,0.802769,...,0.004374,0.598908,6.954946,58.288488,1,1,1,1,4,1
1,1,93.527653,3.372725,1.217548,0.058185,1.620999,0.330805,14.524590,4.714058,6.700123,...,1.065000,1.597009,50.059982,176.442965,1,1,1,1,4,1
2,1,101.527163,3.950959,0.675617,0.000000,2.540638,0.436856,14.242660,2.691121,3.243868,...,0.281250,1.147884,27.677754,119.293643,1,1,1,1,4,1
3,1,81.389119,3.745693,0.558064,0.000000,2.499658,0.501540,10.870846,4.103485,5.607749,...,0.000000,2.261851,62.910781,214.230832,1,1,1,1,4,1
4,1,76.274230,3.713546,0.424643,0.000000,1.780703,1.329019,9.893677,3.403681,5.222974,...,0.000000,1.356905,47.798536,137.342582,1,1,1,1,4,1

In [24]:
#
testdata = data[['Calories/s', 'Fat/s', 'Sat_Fat/s', 'Trans_Fat/s', 'Mono_Fat/s', 'Poly_Fat/s',
                'Carbs/s', 'Fiber/s', 'Sugars/s','Protein/s', 'Cholesterol/s', 'Sodium/s', 'CarbScore', 'CholoScore', 'TotalFatScore','SugarScore','HealthyGradScore','HealthyScore']].copy()
testdata.groupby(["HealthyGradScore"]).describe()

                 Calories/s                                          \
                      count         mean           std          min
HealthyGradScore
0                       8.0  4226.890541   2468.504841  1733.564060
1                      27.0  5591.635240  14990.768377   495.211872
2                     113.0  1023.801083    785.404753   143.031583
3                    1352.0   407.360104    241.775536    89.072408
4                     349.0   192.843738    181.102251     9.314187

                                                                        Fat/s  \
                          25%          50%          75%           max   count
HealthyGradScore
0                 2245.577225  3589.798851  5551.196197   8941.660596     8.0
1                 1331.369768  2107.596169  2559.396118  79486.770230    27.0
2                  442.573443   905.872479  1372.170520   5672.560088   113.0
3                  222.688752   327.730516   542.065344   1701.910000  1352.0
4                   86.870833   149.386919   246.564596   2225.407933   349.0

                              ... SugarScore      HealthyScore                 \
                        mean  ...        75%  max        count mean  std  min
HealthyGradScore              ...
0                 248.207408  ...        0.0  0.0          8.0  0.0  0.0  0.0
1                 439.060946  ...        1.0  1.0         27.0  0.0  0.0  0.0
2                  64.992150  ...        1.0  1.0        113.0  0.0  0.0  0.0
3                  19.029709  ...        1.0  1.0       1352.0  1.0  0.0  1.0
4                  12.630116  ...        1.0  1.0        349.0  1.0  0.0  1.0


                  25%  50%  75%  max
HealthyGradScore
0                 0.0  0.0  0.0  0.0
1                 0.0  0.0  0.0  0.0
2                 0.0  0.0  0.0  0.0
3                 1.0  1.0  1.0  1.0
4                 1.0  1.0  1.0  1.0

[5 rows x 136 columns]

In [25]:
# Assign X (data) and y (target)

X = testdata.drop(['CarbScore', 'CholoScore', 'TotalFatScore','SugarScore','HealthyGradScore','HealthyScore'], axis=1)
y = testdata['HealthyScore']
print(X.shape, y.shape)

(1849, 12) (1849,)

In [26]:
#split data into test and tain
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [27]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
classifier.fit(X_train, y_train)

C:\Users\david\Anaconda3\envs\PythonWebMongo\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\david\Anaconda3\envs\PythonWebMongo\lib\site-packages\sklearn\svm\base.py:929: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [29]:
print(f"Training Data Score: {classifier.score(X_train, y_train)}")
print(f"Testing Data Score: {classifier.score(X_test, y_test)}")

Training Data Score: 0.9776334776334776
Testing Data Score: 0.9762419006479481

In [30]:
predictions = classifier.predict(X_test)
print(f"First 10 Predictions:   {predictions[:10]}")
print(f"First 10 Actual labels: {y_test[:10].tolist()}")

First 10 Predictions:   [1 1 1 1 1 1 1 1 1 1]
First 10 Actual labels: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [32]:
newrecipe = [[700, 300, 18, 0.05, 11, 0.05, 50, 10, 10, 30, 100, 5000]]
newrecipe2 = [X.iloc[1848]]
newpredict = classifier.predict(newrecipe2)

print(newpredict)

[0]

In [33]:
testdata.tail()

,Calories/s,Fat/s,Sat_Fat/s,Trans_Fat/s,Mono_Fat/s,Poly_Fat/s,Carbs/s,Fiber/s,Sugars/s,Protein/s,Cholesterol/s,Sodium/s,CarbScore,CholoScore,TotalFatScore,SugarScore,HealthyGradScore,HealthyScore
1844,5338.606286,355.045011,154.363413,3.761260,143.262646,29.561781,289.387233,30.816380,53.014108,248.153562,1194.114000,7580.005816,0,0,0,0,0,0
1845,3257.983931,260.364165,74.486443,0.000000,136.914404,31.139544,102.115604,19.923578,55.077068,124.305752,600.507210,708.305989,0,0,0,0,0,0
1846,2157.940186,162.476447,30.218429,0.336945,70.826867,50.151219,56.322593,0.000000,55.389837,117.672860,391.291458,4528.224407,0,0,0,0,0,0
1847,1733.564060,137.424477,64.285134,4.613600,51.500743,8.825010,62.326182,2.873500,31.153085,66.005617,371.691791,2245.467982,0,0,0,0,0,0
1848,3921.613770,267.805194,75.269935,1.145553,121.939033,51.582956,258.377348,7.645837,76.117059,115.074626,637.218678,5648.382911,0,0,0,0,0,0

In [35]:
from sklearn_export import Export
# Save using sklearn_export

export = Export(classifier)
export.to_json()